[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "responder_base_classes"
author = "Ian Cleary"
author-email = "Ian Cleary"
home-page = "https://github.com/iancleary/responder-base-classes"
classifiers = ["License :: OSI Approved :: MIT License"]

